version: 0.1

phases:
  build:
    commands:
      - npm installed
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - JRodriguez_Resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
